### ISSUE TITLE
Attribute Bug Introduced In 4d046d3

### ISSUE THREAD

**Issue by reznok** [reznok/GMCAbilitySystem#36]
https://github.com/reznok/GMCAbilitySystem/commit/4d046d33df34078a140c9e6db93aacea80828bbe

This commit created a bug where in the Demo project, stamina regen is being clamped on the client during passive stamina regen, causing a misprediction in Stamina. 

Need to dig into exactly what's causing it, but because this was the Attribute Mod PR, it's likely something about the additive Mod.

**Comment by Packetdancer** [comment]
For what it's worth, I _think_ this may be a bug in the _demo_ rather than the attribute mod commit. Inasmuch as that commit exists on dev as well, and my own simple test GMAS project -- and my actual real project -- both have attributes and effects working fine.

I mean, we probably need to do a good cleanup pass on the demo project _anyway_...

**Comment by petegilb** [comment]
I was debugging this and it has something to do with the modifiers accumulating on the attribute. I pulled dev out of curiosity and there are no problems with dev and the demo other than the reworked ability map
